[email]
smtp_server = "smtp.gmail.com"
smtp_port = 587
sender_email = "hoangnhat2thcsbinhkieu@gmail.com"
sender_password = "hanghgsracfszitr"

[cloudinary]
cloud_name = "djjxor0yp"
api_key = "279843249772723" 
api_secret = "OzQBgBjR5zu4WgR4pNh3en-Mu-I"
